# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd79256cc97c65f9ab7968b879d934ea1bdcf605882d30629d0e9d7c88f8246b90f71ffa11af25813bbb7ce7422396726c81cac70f78a243061558454192431f

test:
  secret_key_base: 078ee3f59e090e547cadc7cca5bb0c434ddecf6421c67122d11c771a9a34502c04dd7d029148f94b7a5643ac0900445e1c994a00c6d1bc31eedec83d3642df20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
